---
name: WWW-ColiPoste
version: 0.01
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: Fetch shipping status from ColiPoste
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  File::Slurp: 0
  HTML::Entities: 0
  HTML::TreeBuilder: 0
  LWP::UserAgent: 0
  perl: 5
build_requires:
  Test::More: 0
provides:
  WWW::ColiPoste:
    file: lib/WWW/ColiPoste.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
